apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: csi-credentials
      namespace: default
    type: Opaque
    stringData: &data
      cloudFolderID: abcdefghiyklmnop1234
      serviceAccountJSON: |
        {
          "id": "folderid12345789etc",
          "service_account_id": "123456789abcdefghiyj",
          "created_at": "2020-05-09T03:14:15Z",
          "key_algorithm": "RSA_2048",
          "public_key": "-----BEGIN PUBLIC KEY-----\n...\n-----END PUBLIC KEY-----\n",
          "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
        }
  - apiVersion: v1
    kind: Secret
    metadata:
      name: csi-credentials
      namespace: kube-system
    type: Opaque
    stringData:
      <<: *data
