---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yandex-csi-controller.name" . }}
type: Opaque
data:
  serviceAccountJSON: {{ .Values.serviceAccountJSON }}
  folderID: {{ .Values.folderID }}